//
// Created by Paul Girault on 20/10/2025.
//

#ifndef LAFARGE_GIRAULT_DESNOES_PROJET_C_PARTIE_1_H
#define LAFARGE_GIRAULT_DESNOES_PROJET_C_PARTIE_1_H

#endif //LAFARGE_GIRAULT_DESNOES_PROJET_C_PARTIE_1_H
